function stripUnsupportedControlChars(value: string) {
  return value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "");
}

function repairTruncatedMathUnicode(value: string) {
  return Array.from(value)
    .map((char) => {
      const codePoint = char.codePointAt(0);
      if (!codePoint) {
        return char;
      }

      if (codePoint >= 0xd400 && codePoint <= 0xd7ff) {
        return String.fromCodePoint(codePoint + 0x10000);
      }

      return char;
    })
    .join("");
}

export function normalizeAcademicText(value: string) {
  const repaired = repairTruncatedMathUnicode(stripUnsupportedControlChars(value)).normalize("NFKD");

  return repaired
    .replace(/\u00A0/g, " ")
    .replace(/[\u2018\u2019\u2032]/g, "'")
    .replace(/[\u201C\u201D]/g, "\"")
    .replace(/[−–—]/g, "-")
    .replace(/[×·]/g, "*")
    .replace(/÷/g, "/")
    .replace(/√/g, "sqrt")
    .replace(/≤/g, "<=")
    .replace(/≥/g, ">=")
    .replace(/≠/g, "!=")
    .replace(/≈/g, "~=")
    .replace(/[→⇒]/g, " -> ")
    .replace(/⇔/g, " <-> ")
    .replace(/[\u20d0-\u20ff]/g, "")
    .replace(/\b([xy])\$/gi, "$1B")
    .replace(/\b([xy])#/gi, "$1A")
    .replace(/\b([uvwt])#/gi, "$1")
    .replace(/\b0#/g, "0")
    .replace(/&(?=[\-+*/= )]|$)/g, "'")
    .replace(/#(?=\s|[=+*/,^;:)\]-]|$)/g, "")
    .replace(/\$+(?=\s|[=+*/,^;:)\]-]|$)/g, "")
    .replace(/\s*\\\s*/g, " ")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
    .normalize("NFC");
}

export function normalizeDocumentText(value: string) {
  const normalized = normalizeAcademicText(value).replace(/\r\n?/g, "\n");

  return normalized
    // Recompose words split with an hyphen at line end.
    .replace(/([A-Za-zÀ-ÿ])-\n([A-Za-zÀ-ÿ])/gu, "$1$2")
    // Preserve paragraph breaks, but turn wrapped single new lines into spaces.
    .replace(/([A-Za-zÀ-ÿ0-9)\]])\n(?=[A-Za-zÀ-ÿ0-9(["])/gu, "$1 ")
    .replace(/\n(?=[a-zà-ÿ])/gu, " ")
    // Reinsert obvious missing separators around punctuation.
    .replace(/([!?;:])(?=[A-Za-zÀ-ÿ0-9])/gu, "$1 ")
    .replace(/([.])(?=[A-ZÀ-ÖØ-Þ])/gu, "$1 ")
    .replace(/([,)])(?=[A-Za-zÀ-ÿ])/gu, "$1 ")
    .replace(/([\])}])(?=[A-Za-zÀ-ÿ])/gu, "$1 ")
    // Normalize inner spacing without flattening paragraphs.
    .replace(/[ \t]+/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .split("\n")
    .map((line) => line.trim())
    .join("\n")
    .trim();
}

export function cleanGeneratedContent(value: string) {
  // Use light sanitizer (not normalizeDocumentText) to preserve LaTeX backslashes
  // generated by AI (e.g. \mathbb{N}, \frac{a}{b}, \sqrt{x})
  let cleaned = sanitizeAiText(value)
    .replace(/([!?;:])(?=[A-Za-zÀ-ÿ0-9])/gu, "$1 ")
    .replace(/([.])(?=[A-ZÀ-ÖØ-Þ])/gu, "$1 ")
    .replace(/([,)])(?=[A-Za-zÀ-ÿ])/gu, "$1 ");

  cleaned = cleaned
    .replace(/\b\d+\s*(?:chapitre|partie|section)\s*\d+(?:\.\d+)*\b/giu, "")
    .replace(/\b(?:chapitre|partie|section)\s*\d+(?:\.\d+)*\b/giu, "")
    .replace(/\b\d+\s+\d+(?:\.\d+){1,}\b/gu, "")
    .replace(/\(\s*p\.?\s*\d+\s*\)/giu, "")
    .replace(/\bp\.?\s*\d+\b/giu, "")
    .replace(/\s{2,}/g, " ")
    .replace(/ *([,;:.!?]) */g, "$1 ")
    .replace(/\s+\)/g, ")")
    .replace(/\(\s+/g, "(")
    .trim();

  const firstSentenceMatch = cleaned.match(/^([^.!?]+[.!?])\s*([\s\S]*)$/u);
  if (firstSentenceMatch) {
    const firstSentence = firstSentenceMatch[1].trim();
    const remainder = firstSentenceMatch[2].trim();
    const firstWord = firstSentence.match(/[A-Za-zÀ-ÿ]/u)?.[0] ?? "";
    const wordCount = firstSentence.split(/\s+/).filter(Boolean).length;

    if (firstWord === firstWord.toLowerCase() && wordCount <= 6 && remainder) {
      cleaned = remainder;
    }
  }

  cleaned = cleaned.replace(/([.!?]\s+)([a-zà-ÿ])/gu, (_, prefix: string, letter: string) => `${prefix}${letter.toUpperCase()}`);

  if (/^[a-zà-ÿ]/u.test(cleaned)) {
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  }

  return cleaned
    .replace(/\s{2,}/g, " ")
    .replace(/ \./g, ".")
    .replace(/ ,/g, ",")
    .trim();
}

export function normalizeFormulaText(value: string) {
  // Use sanitizeAiText instead of normalizeAcademicText to preserve LaTeX backslashes.
  // normalizeAcademicText strips all backslashes via /\s*\\\s*/g → " " (line 47).
  return sanitizeAiText(value)
    .replace(/\u00A0/g, " ")
    .replace(/[−–—]/g, "-")
    .replace(/[×·]/g, "*")
    .replace(/÷/g, "/")
    .replace(/√/g, "sqrt")
    .replace(/≤/g, "<=")
    .replace(/≥/g, ">=")
    .replace(/≠/g, "!=")
    .replace(/≈/g, "~=")
    .replace(/[→⇒]/g, " -> ")
    .replace(/^\$\$([\s\S]+)\$\$$/g, "$1")
    .replace(/^\\\(([\s\S]+)\\\)$/g, "$1")
    .replace(/^\$([\s\S]+)\$$/g, "$1")
    .replace(/\\(?:d?frac)\{([^{}]+)\}\{([^{}]+)\}/g, "($1)/($2)")
    .replace(/\\sqrt\{([^{}]+)\}/g, "sqrt($1)")
    .replace(/\\cdot|\\times/g, " * ")
    .replace(/\\pm/g, " +/- ")
    .replace(/\\leq?|≤/g, " <= ")
    .replace(/\\geq?|≥/g, " >= ")
    .replace(/\\neq|≠/g, " != ")
    .replace(/\\approx|≈/g, " ~= ")
    .replace(/\\to|→/g, " -> ")
    .replace(/\\infty|∞/g, " inf ")
    .replace(/\\mathbb\{R\}/g, "R")
    .replace(/\\mathbb\{N\}/g, "N")
    .replace(/\\mathbb\{Z\}/g, "Z")
    .replace(/\\mathbb\{Q\}/g, "Q")
    .replace(/\\mathbb\{C\}/g, "C")
    .replace(/\^\{([^}]+)\}/g, "^($1)")
    .replace(/_\{([^}]+)\}/g, "_$1")
    .replace(/\s*=\s*/g, " = ")
    .replace(/\s*\+\s*/g, " + ")
    .replace(/\s*-\s*/g, " - ")
    .replace(/\s*\*\s*/g, " * ")
    .replace(/\s*\/\s*/g, " / ")
    .replace(/\s*;\s*/g, " ; ")
    .replace(/\s*,\s*/g, ", ")
    .replace(/\(\s+/g, "(")
    .replace(/\s+\)/g, ")")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function looksLikeFormula(value: string) {
  const cleaned = normalizeFormulaText(value);

  if (!cleaned || /^(les|partie|chapitre|section)\b/i.test(cleaned)) {
    return false;
  }

  return /[=^]/.test(cleaned)
    || /\b(?:sqrt|det|ln|exp|lim|f'|u_n|v_n|w_n|P\(|Q\(|e\^)\b/i.test(cleaned)
    || /\b(?:derivee|exponentielle|suite|fonction|equation|inequation|vecteur|distance|milieu|probabilite|matrice)\b/i.test(cleaned);
}

export function buildFormulaSignature(value: string) {
  return normalizeFormulaText(value)
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/\(\s*/g, "(")
    .replace(/\s*\)/g, ")")
    .replace(/[*]/g, "*")
    .replace(/;\s*/g, ";")
    .replace(/,+/g, ",")
    .trim();
}

export function formulasEquivalent(left: string, right: string) {
  const leftSignature = buildFormulaSignature(left);
  const rightSignature = buildFormulaSignature(right);

  if (!leftSignature || !rightSignature) {
    return false;
  }

  if (leftSignature === rightSignature) {
    return true;
  }

  return (
    (leftSignature.length >= 10 && rightSignature.includes(leftSignature))
    || (rightSignature.length >= 10 && leftSignature.includes(rightSignature))
  );
}

export function extractFormulaCandidates(sourceText: string) {
  const normalizedSource = normalizeAcademicText(sourceText);
  const candidates: string[] = [];

  const pushCandidate = (value: string) => {
    const cleaned = normalizeFormulaText(value);
    const operatorCount = (cleaned.match(/[=+\-*/^<>]/g) ?? []).length;
    const longWordCount = cleaned.match(/[A-Za-z]{4,}/g)?.length ?? 0;

    if (!cleaned || cleaned.length < 4 || cleaned.length > 160) {
      return;
    }

    if (!looksLikeFormula(cleaned) && !/[=^]/.test(cleaned)) {
      return;
    }

    if (/^(definition|exemple|propriete|theoreme|methode|chapitre|partie|cours)\b/i.test(cleaned)) {
      return;
    }

    if (longWordCount >= 9 && operatorCount < 2) {
      return;
    }

    if (/^[A-Za-z][A-Za-z\s]{18,}$/.test(cleaned) && operatorCount === 0) {
      return;
    }

    candidates.push(cleaned);
  };

  for (const rawLine of normalizedSource.split(/\n+/)) {
    const line = rawLine.trim();
    if (!line) {
      continue;
    }

    pushCandidate(line);

    if (line.includes(":")) {
      const afterColon = line.split(":").slice(1).join(":");
      pushCandidate(afterColon);
    }

    for (const chunk of line.split(/[;|]/)) {
      pushCandidate(chunk);
    }
  }

  return [...new Set(candidates.map((item) => buildFormulaSignature(item)).filter(Boolean))]
    .map((signature) => candidates.find((item) => buildFormulaSignature(item) === signature) ?? "")
    .filter(Boolean);
}

export function sanitizeText(value: string) {
  return normalizeAcademicText(value).replace(/\r/g, "").trim();
}

export function sanitizeJsonValue<T>(value: T): T {
  if (typeof value === "string") {
    return sanitizeText(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => sanitizeJsonValue(item)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entryValue]) => [key, sanitizeJsonValue(entryValue)]),
    ) as T;
  }

  return value;
}

/**
 * Light sanitizer for AI-generated content.
 * Only strips control characters and normalizes whitespace — does NOT touch
 * backslashes, so LaTeX commands like \frac, \mathbb, \sqrt are preserved.
 */
export function sanitizeAiText(value: string) {
  return stripUnsupportedControlChars(value)
    .replace(/\r/g, "")
    .replace(/\u00A0/g, " ")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function sanitizeAiJsonValue<T>(value: T): T {
  if (typeof value === "string") {
    return sanitizeAiText(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => sanitizeAiJsonValue(item)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entryValue]) => [key, sanitizeAiJsonValue(entryValue)]),
    ) as T;
  }

  return value;
}
